server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  data:
    mongodb:
      database: users_db
      uri: mongodb+srv://user:kYUIJhO7FTID9cQt@tsg-alpha-db.fpya4bj.mongodb.net/
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
  rsocket:
    server:
      port: 6565
      transport: websocket
      mapping-path: /rsocket

redis:
  timeout: 2000

jwt:
  token:
    timeout: 1800000
    refreshTimeout: 604800000
    key: sam's silly little key